name: Tesing ## name of the workflow

on:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: echo ${{secrets.ANDROID_FIREBASE_APP_ID}}
      - name: My Action
        run: echo ${{secrets.ANDROID_FIREBASE_APP_ID_TY}}
